# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME', '/readme_orig/']

# Site Settings
title: "Expressive Encounters Workshop"
email: "viktor.schmuck@kcl.ac.uk"
description: ""
baseurl: "/2024"
url: "https://expressive-encounters-workshop.github.io"
permalink: "/blog/:title"

# Organizer Info
organizerName: ""
organizerAlternateName: ""
organizerDescription: ""
organizerEmail: "viktor.schmuck@kcl.ac.uk"
organizerLogo: ""
organizerLink: ""




# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/schedule/", text: "Schedule"}
 - {permalink: "/speakers/", text: "Speakers"}
 - {permalink: "/importantdates/", text: "Important Dates"}
 - {permalink: "/blog/", text: "Blog"}
 - {permalink: "/acceptedpapers/", text: "Accepted Papers"}

# Hero Block
heroImage: "hero.jpg"
heroTitle: "Expressive Encounters Workshop"
eventDate: "September 29, 2024"
typeoutTextValues: 'Expressive Encounters Workshop'

# About Block
aboutTitle: "Expressive Encounters Workshop"
aboutBlock:
 - {title: "Conference", image: "conference.jpg", text: "The biggest Google related event in the country carefully crafted for you by GDG community! Awesome speakers and lots of fun!" }
#  - {title: "Workshops", image: "workshop.jpg", text: "Full-day of workshops, hands-on experience, hacking and debugging. Come and tame your favourite technology!" }
#  - {title: "Hackathon", image: "hackathon.jpg", text: "Full-day freestyle hackathon! Want some real team building on friday? Grab your team and join our hackathon!" }

# Statistic Block
#statisticBlockImage: "statistic.jpg"
#statisticBlock:
# - {count: "350", specialCharacter: "+", info: "attendees", detail: "from everywhere"}
# - {count: "48", specialCharacter: "+", info: "hours", detail: "of pure Google technologies"}
# - {count: "20", specialCharacter: "+", info: "speakers", detail: "from country and beyond"}
# - {count: "3", specialCharacter: "", info: "parallel tracks", detail: "plus entertainment lounge"}

# Latest News Block

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 3
rockstarSpeakersTitle: "Speakers"
rockstarSpeakersButtonText: "View Speaker Details"



# Partners Block
organizersTitle: "Organizers"
partnersTitle: "Partners"


# Footer

footerBlocks:
 -
  title: "Linksssssss"
  links:
   - {link: "https://sairlab.github.io/", text: "Social AI & Robotics (SAIR) Laboratory"}

 -
  title: "Contactsssss"
  links:
   - {link: "mailto:viktor.schmuck@kcl.ac.uk", text: "viktor.schmuck@kcl.ac.uk"}

# Speakers List Block
showSessions: true

# Team Block
# teamBlockTitle: "About us"
# aboutUs: "Google's services have become synonymous with simple things online. Number of technological innovations and IT industries in which Google is creating new products is enormous. It's hard to get to know all of them, but realistic. This is why people have started to gather in small local groups and share their experience. Later, the following groups have been called Google Developer Groups. GDGs can take many forms -- from just a few people getting together to watch some videos, to large gatherings with demos, tech talks, hackathons and conferences."
collections:
  papers:
    output: true
    permalink: "papers/:title"